# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the source code.
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      # Step 2: Build the project using the JS library and explicit source files.
      - name: Build Project
        run: |
          mkdir build
          docker run --rm \
            -v $GITHUB_WORKSPACE:/src \
            trzeci/emscripten:sdk-incoming-64bit \
            bash -c "cd /src && emcc -o build/index.html \
            src/main.c src/text_renderer.c \
            -Wall -s USE_SDL=2 -s USE_SDL_TTF=2 \
            --preload-file assets@assets -s ALLOW_MEMORY_GROWTH \
            --js-library src/library_web.js \
            --shell-file src/template.html"

      # Step 3: Deploy the contents of the 'build' directory.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The Personal Access Token for the target repository
          personal_token: ${{ secrets.SIGVIZ }}
          # The repository to push the build results to
          external_repository: SigViz/sigviz.github.io
          # The directory in this repository that contains the built website
          publish_dir: ./build