# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the source code.
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      # Step 2: Explicitly build the Raylib port first.
      # This ensures the library is compiled and available before we need it.
      - name: Build Raylib Port
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/src \
            -w /src \
            trzeci/emscripten:sdk-incoming-64bit \
            embuilder build raylib

      # Step 3: Build your project using the Makefile.
      # This will now find the pre-built Raylib library.
      - name: Build Project
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/src \
            -w /src \
            trzeci/emscripten:sdk-incoming-64bit \
            make web

      # Step 4: Deploy the built files to your other repository.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.SIGVIZ }}
          external_repository: SigViz/sigviz.github.io
          publish_dir: ./
          keep_files: false