# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the source code.
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      # Step 2: Build the project using the official Emscripten SDK Docker image.
      # This image is standardized and will correctly build the raylib port.
      - name: Build Project
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/src \
            -w /src \
            emscripten/emsdk:latest \
            make web

      # Step 3: Deploy the built files to your GitHub Pages repository.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.SIGVIZ }}
          external_repository: SigViz/sigviz.github.io
          publish_dir: ./
          keep_files: false