# .github/workflows/test.yml

name: Emscripten Action Test

on:
  push:
    branches:
      - main # Or whatever your main branch is

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Setup Emscripten Action
        uses: emscripten-core/setup-emscripten@v4